
package br.ulbra.view;

import br.ulbra.entity.Num;
import javax.swing.JOptionPane;

public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        edCoD = new javax.swing.JTextField();
        btexcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PainelP = new javax.swing.JPanel();
        btsalvarNum = new javax.swing.JButton();
        ednumero = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        lbPainel = new javax.swing.JLabel();
        btimpar = new javax.swing.JButton();
        btpar = new javax.swing.JButton();
        edbuscar = new javax.swing.JTextField();
        btmaximo = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        lbcd = new javax.swing.JLabel();
        lbN = new javax.swing.JLabel();
        btminimo = new javax.swing.JButton();
        btOrdenar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edCodA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ednumNovo = new javax.swing.JTextField();
        btalterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        atlistaN = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitu.setText("GERENCIAMENTO");
        jPanel1.add(lbTitu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DELETAR"));

        btexcluir.setText("EXCLUIR");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("INFORME O CÓDIGO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(edCoD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btexcluir))
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edCoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexcluir)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 160, 100));

        PainelP.setBorder(javax.swing.BorderFactory.createTitledBorder("ADICIONAR NÚMERO"));

        btsalvarNum.setText("SALVAR");
        btsalvarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarNumActionPerformed(evt);
            }
        });

        ednumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednumeroActionPerformed(evt);
            }
        });

        btBuscar.setText("BUSCAR");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btListar.setText("LISTAR");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        lbPainel.setText("SELECIONAR NÚMEROS");

        btimpar.setText("IMPAR");
        btimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimparActionPerformed(evt);
            }
        });

        btpar.setText("PAR");
        btpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btparActionPerformed(evt);
            }
        });

        btmaximo.setText("MAIOR");
        btmaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmaximoActionPerformed(evt);
            }
        });

        btC.setText("CRESCENTE");

        btD.setText("DECRESCENTE");

        lbcd.setText("ORDEM");

        lbN.setText("NÚMERO");

        btminimo.setText("MENOR");
        btminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminimoActionPerformed(evt);
            }
        });

        btOrdenar.setText("ORDENAR");
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPLayout = new javax.swing.GroupLayout(PainelP);
        PainelP.setLayout(PainelPLayout);
        PainelPLayout.setHorizontalGroup(
            PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btmaximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btminimo)
                .addGap(188, 188, 188))
            .addGroup(PainelPLayout.createSequentialGroup()
                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPainel)
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addComponent(btpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btimpar)
                        .addGap(34, 34, 34)
                        .addComponent(lbN))
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addComponent(ednumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btsalvarNum)))
                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(edbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                                        .addComponent(lbcd)
                                        .addGap(78, 78, 78))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                                        .addComponent(btC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btD)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPLayout.createSequentialGroup()
                                .addComponent(btOrdenar)
                                .addGap(75, 75, 75))))))
        );
        PainelPLayout.setVerticalGroup(
            PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPLayout.createSequentialGroup()
                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ednumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btListar)
                            .addComponent(btBuscar)
                            .addComponent(edbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btsalvarNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbcd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btD)
                            .addComponent(btC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btOrdenar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelPLayout.createSequentialGroup()
                        .addComponent(lbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btpar)
                            .addComponent(btimpar)
                            .addComponent(lbN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btmaximo)
                            .addComponent(btminimo))
                        .addGap(28, 28, 28))))
        );

        jPanel1.add(PainelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 470, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ATUALIZAR"));

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("NOVO NÚMERO");

        ednumNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ednumNovoActionPerformed(evt);
            }
        });

        btalterar.setText("ALTERAR");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(edCodA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ednumNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btalterar)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edCodA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ednumNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btalterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 90));

        atlistaN.setColumns(20);
        atlistaN.setRows(5);
        jScrollPane2.setViewportView(atlistaN);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   Num numero = new Num();
    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
           numero.excluir(Integer.parseInt(edCoD.getText()));
      
       btListar.doClick();     
         
      
    }//GEN-LAST:event_btexcluirActionPerformed

    private void btsalvarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarNumActionPerformed
    numero.salvar(Integer.parseInt(ednumero.getText()));
     btListar.doClick();     
     ednumero.setText(null);
    
    }//GEN-LAST:event_btsalvarNumActionPerformed

    private void ednumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ednumeroActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
       numero.alterar(Integer.parseInt(edCodA.getText()), Integer.parseInt(ednumNovo.getText()));
         btListar.doClick();
    }//GEN-LAST:event_btalterarActionPerformed

    private void ednumNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ednumNovoActionPerformed
       
    }//GEN-LAST:event_ednumNovoActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
       atlistaN.setText(numero.getNum());
    }//GEN-LAST:event_btListarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
      int n = numero.buscar(Integer.parseInt(edbuscar.getText()));
        atlistaN.setText(String.valueOf(n));
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btparActionPerformed
         atlistaN.setText(numero.listarPares());
    }//GEN-LAST:event_btparActionPerformed

    private void btimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimparActionPerformed
        atlistaN.setText(numero.listarImpares());
    }//GEN-LAST:event_btimparActionPerformed

    private void btmaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmaximoActionPerformed
     int maximo=numero.getNumeroMaximo();
    JOptionPane.showMessageDialog(null, "Número Máximo: " + maximo);
    }//GEN-LAST:event_btmaximoActionPerformed

    private void btminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminimoActionPerformed
         int minimo = numero.getNumeroMinimo();
    JOptionPane.showMessageDialog(null, "Número Mínimo: " + minimo);
    }//GEN-LAST:event_btminimoActionPerformed

    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
    numero.ordenarLista();
        btListar.doClick();
    }//GEN-LAST:event_btOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelP;
    private javax.swing.JTextArea atlistaN;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btListar;
    private javax.swing.JToggleButton btOrdenar;
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btimpar;
    private javax.swing.JButton btmaximo;
    private javax.swing.JButton btminimo;
    private javax.swing.JButton btpar;
    private javax.swing.JButton btsalvarNum;
    private javax.swing.JTextField edCoD;
    private javax.swing.JTextField edCodA;
    private javax.swing.JTextField edbuscar;
    private javax.swing.JTextField ednumNovo;
    private javax.swing.JTextField ednumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbN;
    private javax.swing.JLabel lbPainel;
    private javax.swing.JLabel lbTitu;
    private javax.swing.JLabel lbcd;
    // End of variables declaration//GEN-END:variables
}
